version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: aignatov2/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: aignatov2/foodgram_frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  db_data:
  static_value:
  media_value: